const KARNATAKA_CITIES = [
  { city: "Bagalkot", state: "Karnataka" },
  { city: "Ballari", state: "Karnataka" },
  { city: "Belgaum", state: "Karnataka" },
  { city: "Belagavi", state: "Karnataka" },
  { city: "Bellary", state: "Karnataka" },
  { city: "Bangalore", state: "Karnataka" },
  { city: "Bidar", state: "Karnataka" },
  { city: "Chikballapur", state: "Karnataka" },
  { city: "Chikmagalur", state: "Karnataka" },
  { city: "Chitradurga", state: "Karnataka" },
  { city: "Davanagere", state: "Karnataka" },
  { city: "Dharwad", state: "Karnataka" },
  { city: "Gadag", state: "Karnataka" },
  { city: "Gulbarga", state: "Karnataka" },
  { city: "Hassan", state: "Karnataka" },
  { city: "Hubli", state: "Karnataka" },
  { city: "Kodagu", state: "Karnataka" },
  { city: "Kolar", state: "Karnataka" },
  { city: "Koppal", state: "Karnataka" },
  { city: "Mandya", state: "Karnataka" },
  { city: "Mangalore", state: "Karnataka" },
  { city: "Mysore", state: "Karnataka" },
  { city: "Raiichur", state: "Karnataka" },
  { city: "Ramanagara", state: "Karnataka" },
  { city: "Shimoga", state: "Karnataka" },
  { city: "Trivandum", state: "Karnataka" },
  { city: "Tumkur", state: "Karnataka" },
  { city: "Udupi", state: "Karnataka" },
  { city: "Uttara Kannada", state: "Karnataka" },
  { city: "Vijayanagara", state: "Karnataka" },
  { city: "Yadgir", state: "Karnataka" },
];

module.exports = KARNATAKA_CITIES;
